-- Add new columns to bookings table if they don't exist
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS vehicle_reg VARCHAR(20) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS postcode VARCHAR(10) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS service_type VARCHAR(100) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS completed_at DATETIME DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS service_performed VARCHAR(255) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cost VARCHAR(50) DEFAULT NULL;
